# Generated by Django 4.1.4 on 2022-12-10 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('haha', 'Funny'), ('ohhh', 'amazed'), ('nahh', 'Not Funny')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('special', 'special'), ('Far', 'Far'), ('Very close', 'close'), ('to be roasted', 'tobe')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bod', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('level', models.CharField(choices=[('comedian', 'comedian'), ('pro', 'pro'), ('amatuer', 'amatuer'), ('roaster', 'roaster'), ('spectator', 'spectator')], default='spectator', max_length=50)),
                ('bio', models.CharField(default='bio', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='media/jokes_photo/')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('time_posted', models.TimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ManyToManyField(related_name='reacted', to='core.reaction')),
                ('stage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.roast')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreact', to='core.reaction'),
        ),
    ]
